### ISSUE TITLE
Npm is not defined

### ISSUE THREAD

**Issue by KristerV** [AkashaProject/meteor-shelljs#1]
Your plugin does not seem to work. On my local server I get errors
![screenshot_2015-12-04_10-20-57](https://cloud.githubusercontent.com/assets/2750622/11584934/d19af3da-9a70-11e5-8c28-3b12db507a6d.png)

but I actually manager to deploy without checking, and on live server Chrome says

![screenshot_2015-12-04_10-21-14](https://cloud.githubusercontent.com/assets/2750622/11584944/dfb2fdf0-9a70-11e5-8f6f-d1c207ec6282.png)

And nothing at all is showing on my site.

Either rething dependencies or say something in the readme.

**Comment by kenshyx** [comment]
Hello, this plugin is supposed to work only server side. There was an error on atmosphere, it was adding the file on client side also that's why you got that error on browser. I submitted a new version on atmosphere, let me know if there are still problems.

**Comment by KristerV** [comment]
nice, thanks. I shall close this for now as ShellJS didn't fulfill my needs anyway. I'm sure it's better now.
